"""Persisted regression scoreboard.

Appends one row per Proving Ground run to ``proving_ground/scoreboard.jsonl`` and
regenerates a human-readable ``proving_ground/SCOREBOARD.md`` so the climb (and
any regression) is visible across iterations. This is the committed history that
PROJECT.md references.
"""
from __future__ import annotations

import json
import os
import time
from typing import Dict, List

_HERE = os.path.dirname(__file__)
_JSONL = os.path.join(_HERE, "scoreboard.jsonl")
_MD = os.path.join(_HERE, "SCOREBOARD.md")

_CATS = [
    "mathematical_reasoning", "code_generation", "code_debugging", "logical_reasoning",
    "named_entity_recognition", "sentiment_analysis", "text_summarization", "factual_knowledge",
]


def append_run(entry: Dict) -> None:
    entry = {"ts": time.strftime("%Y-%m-%d %H:%M:%S"), **entry}
    with open(_JSONL, "a", encoding="utf-8") as fh:
        fh.write(json.dumps(entry) + "\n")
    _render()


def _load() -> List[Dict]:
    if not os.path.exists(_JSONL):
        return []
    rows = []
    with open(_JSONL, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def _render() -> None:
    rows = _load()
    lines = [
        "# ZeroProof Proving Ground — Regression Scoreboard",
        "",
        "_Auto-generated by `proving_ground/run.py`. Each row is one iteration._",
        "",
        "Generalized accuracy is measured on **generated paraphrase/harder/adversarial "
        "variants**, never the public sample tasks. `det` = deterministic categories "
        "(model-independent); `all` includes model-dependent categories (needs the "
        "bundled model, i.e. run inside the image).",
        "",
        "| Run (UTC) | Label | Seeds | Model | det acc | all acc | FW tokens | Guard |",
        "| :-- | :-- | :-- | :-- | :-- | :-- | :-- | :-- |",
    ]
    for r in rows:
        lines.append(
            f"| {r.get('ts','')} | {r.get('label','')} | {r.get('seeds','')} | "
            f"{r.get('model','')} | {r.get('det_acc','')}% | {r.get('all_acc','')}% | "
            f"{r.get('fireworks_tokens','')} | {r.get('guard','')} |"
        )
    lines += ["", "## Latest per-category (generalized) accuracy", ""]
    if rows:
        last = rows[-1]
        percat = last.get("per_category", {})
        lines.append("| Category | Accuracy | Model-dependent |")
        lines.append("| :-- | :-- | :-- |")
        for c in _CATS:
            info = percat.get(c, {})
            lines.append(f"| {c} | {info.get('acc','n/a')}% ({info.get('passed','?')}/{info.get('total','?')}) | {info.get('model_dependent', False)} |")
    with open(_MD, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def render_path() -> str:
    return _MD
